name: number_pagination
description: Pagination using number, such as the classic web style pagination.
version: 1.0.0
homepage: https://github.com/xpwmaosldk/number_pagination

screenshots:
  - description: "It shows how it works at init"
    path: screenshots/screenshots1.png
  - description: "It shows how it works at perfromed 1 button"
    path: screenshots/screenshots2.png

environment:
  sdk: ">=2.12.0 <3.0.0"
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
